#//jdbc:postgresql://db.alwxugihihnbbvjrzpes.supabase.co:5432/postgres?user=postgres&password=Remoto.2002**

spring.application.name=unieventos
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://db.alwxugihihnbbvjrzpes.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Remoto.2002**

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect