spring.application.name=unieventos
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.alwxugihihnbbvjrzpes
spring.datasource.password=fiLz8qIbneFrc3Np
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

github.token=${GITHUB_TOKEN}
github.repo=${GITHUB_REPO}

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
server.tomcat.max-swallow-size=20MB
server.tomcat.max-http-form-post-size=20MB